env/bin/python main.py analyze-terms --group AFJ1 | tee output/terms_analysis_AFJ1.log &
env/bin/python main.py analyze-terms --group AMN1 | tee output/terms_analysis_AMN1.log &
env/bin/python main.py analyze-terms --group API1 | tee output/terms_analysis_API1.log &
env/bin/python main.py analyze-terms --group ARE1 | tee output/terms_analysis_ARE1.log &
env/bin/python main.py analyze-terms --group ASA1 | tee output/terms_analysis_ASA1.log &
env/bin/python main.py analyze-terms --group AZC1 | tee output/terms_analysis_AZC1.log &
env/bin/python main.py analyze-terms --group CJK1 | tee output/terms_analysis_CJK1.log &
env/bin/python main.py analyze-terms --group EKE1 | tee output/terms_analysis_EKE1.log &
env/bin/python main.py analyze-terms --group FLL1 | tee output/terms_analysis_FLL1.log &
env/bin/python main.py analyze-terms --group ICE1 | tee output/terms_analysis_ICE1.log &
env/bin/python main.py analyze-terms --group IDE1 | tee output/terms_analysis_IDE1.log &
env/bin/python main.py analyze-terms --group IDG1 | tee output/terms_analysis_IDG1.log &
env/bin/python main.py analyze-terms --group IDO1 | tee output/terms_analysis_IDO1.log &
env/bin/python main.py analyze-terms --group IHG1 | tee output/terms_analysis_IHG1.log &
env/bin/python main.py analyze-terms --group IHL1 | tee output/terms_analysis_IHL1.log &
env/bin/python main.py analyze-terms --group IHL2 | tee output/terms_analysis_IHL2.log &
env/bin/python main.py analyze-terms --group JTM1 | tee output/terms_analysis_JTM1.log &
env/bin/python main.py analyze-terms --group PBZ1 | tee output/terms_analysis_PBZ1.log &
env/bin/python main.py analyze-terms --group RPE1 | tee output/terms_analysis_RPE1.log &
env/bin/python main.py analyze-terms --group RPI1 | tee output/terms_analysis_RPI1.log &
env/bin/python main.py analyze-terms --group RZA1 | tee output/terms_analysis_RZA1.log &
wait
